<a href="https://colab.research.google.com/github/RenataRSBriet/ciencia-de-dados-e-sistemas-inteligentes/blob/master/PreProcessamento_Censo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
from google.colab import drive
drive.mount('/content/drive')
caminho = "/content/drive/MyDrive/Aula/MaterialApoio/"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [38]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
import pickle

In [39]:
base_censo = pd.read_csv(caminho + "census.csv")

In [40]:
base_censo

age          workclass  ...  native-country  income
0       39          State-gov  ...   United-States   <=50K
1       50   Self-emp-not-inc  ...   United-States   <=50K
2       38            Private  ...   United-States   <=50K
3       53            Private  ...   United-States   <=50K
4       28            Private  ...            Cuba   <=50K
...    ...                ...  ...             ...     ...
32556   27            Private  ...   United-States   <=50K
32557   40            Private  ...   United-States    >50K
32558   58            Private  ...   United-States   <=50K
32559   22            Private  ...   United-States   <=50K
32560   52       Self-emp-inc  ...   United-States    >50K

[32561 rows x 15 columns]

In [41]:
# age - discreta
# workclass - não ordinal é nominal
# final - é contínua
# education - ordinal (interpretação)
# anos - é discreto (número de anos)
# estado civil, posição família - nominal
# ocupação, raça, sexo - nominais
# horas trabalhadas - discreta
# país -  nominal
# classe - é ordinal
base_censo.describe()

age  final-weight  ...  capital-loos  hour-per-week
count  32561.000000  3.256100e+04  ...  32561.000000   32561.000000
mean      38.581647  1.897784e+05  ...     87.303830      40.437456
std       13.640433  1.055500e+05  ...    402.960219      12.347429
min       17.000000  1.228500e+04  ...      0.000000       1.000000
25%       28.000000  1.178270e+05  ...      0.000000      40.000000
50%       37.000000  1.783560e+05  ...      0.000000      40.000000
75%       48.000000  2.370510e+05  ...      0.000000      45.000000
max       90.000000  1.484705e+06  ...   4356.000000      99.000000

[8 rows x 6 columns]

In [42]:
base_censo.isnull().sum()

age               0
workclass         0
final-weight      0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loos      0
hour-per-week     0
native-country    0
income            0
dtype: int64

## Divisão entre Previsores e Classes

In [43]:
base_censo.columns

Index(['age', 'workclass', 'final-weight', 'education', 'education-num',
       'marital-status', 'occupation', 'relationship', 'race', 'sex',
       'capital-gain', 'capital-loos', 'hour-per-week', 'native-country',
       'income'],
      dtype='object')

In [44]:
x_census = base_censo.iloc[:, 0:14].values

In [45]:
x_census

array([[39, ' State-gov', 77516, ..., 0, 40, ' United-States'],
       [50, ' Self-emp-not-inc', 83311, ..., 0, 13, ' United-States'],
       [38, ' Private', 215646, ..., 0, 40, ' United-States'],
       ...,
       [58, ' Private', 151910, ..., 0, 40, ' United-States'],
       [22, ' Private', 201490, ..., 0, 20, ' United-States'],
       [52, ' Self-emp-inc', 287927, ..., 0, 40, ' United-States']],
      dtype=object)

In [46]:
y_census = base_censo.iloc[:, 14].values

In [47]:
y_census

array([' <=50K', ' <=50K', ' <=50K', ..., ' <=50K', ' <=50K', ' >50K'],
      dtype=object)

## Tratamento de atributos categóricos

## LabelEncoder

Transforma em números inteiros as categorias de cada atributo categórico não binário (mais de 2 categorias)

In [48]:
x_census[:,1]

array([' State-gov', ' Self-emp-not-inc', ' Private', ..., ' Private',
       ' Private', ' Self-emp-inc'], dtype=object)

In [49]:
label_encoder_teste = LabelEncoder()
teste = label_encoder_teste.fit_transform(x_census[:,1])
teste

array([7, 6, 4, ..., 4, 4, 5])

In [50]:
x_census[0]

array([39, ' State-gov', 77516, ' Bachelors', 13, ' Never-married',
       ' Adm-clerical', ' Not-in-family', ' White', ' Male', 2174, 0, 40,
       ' United-States'], dtype=object)

In [51]:
label_encoder_workclass = LabelEncoder()
label_encoder_education = LabelEncoder()
label_encoder_marital = LabelEncoder()
Label_encoder_occupation = LabelEncoder()
label_encoder_relationship = LabelEncoder()
label_encoder_race = LabelEncoder()
label_encoder_sex = LabelEncoder()
label_encoder_country = LabelEncoder()

In [52]:
x_census[:,1] = label_encoder_workclass.fit_transform(x_census[:,1])
x_census[:,1] = label_encoder_education.fit_transform(x_census[:,3])
x_census[:,1] = label_encoder_marital.fit_transform(x_census[:,5])
x_census[:,1] = Label_encoder_occupation.fit_transform(x_census[:,6])
x_census[:,1] = label_encoder_relationship.fit_transform(x_census[:,7])
x_census[:,1] = label_encoder_race.fit_transform(x_census[:,8])
x_census[:,1] = label_encoder_sex.fit_transform(x_census[:,9])
x_census[:,1] = label_encoder_country.fit_transform(x_census[:,13])

In [53]:
x_census[0]

array([39, 39, 77516, ' Bachelors', 13, ' Never-married', ' Adm-clerical',
       ' Not-in-family', ' White', ' Male', 2174, 0, 40, ' United-States'],
      dtype=object)

In [54]:
x_census

array([[39, 39, 77516, ..., 0, 40, ' United-States'],
       [50, 39, 83311, ..., 0, 13, ' United-States'],
       [38, 39, 215646, ..., 0, 40, ' United-States'],
       ...,
       [58, 39, 151910, ..., 0, 40, ' United-States'],
       [22, 39, 201490, ..., 0, 20, ' United-States'],
       [52, 39, 287927, ..., 0, 40, ' United-States']], dtype=object)

## OneHotEncoder

Transforma em numeros binarios (0 e 1) as categorias de cada atributo categorico nao binario (mais de 2 categorias).
Cada categoria de um atributo se transforma em uma nova coluna (atributo). Exemplo: atributo "workclass" com 9 categorias se transforma em 9 novos atributos. Cada linha tera valor 1 na coluna referente a categoria original e 0 nas outras colunas.

In [55]:
np.unique(base_censo['workclass'])

array([' ?', ' Federal-gov', ' Local-gov', ' Never-worked', ' Private',
       ' Self-emp-inc', ' Self-emp-not-inc', ' State-gov', ' Without-pay'],
      dtype=object)

In [56]:
len(np.unique(base_censo['workclass']))

9

In [57]:
len(np.unique(base_censo['occupation']))

15

In [66]:
# as outras colunas serao apagadas
onehotencoder = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(), [1,3,5,6,7,8,9,13])], remainder='passthrough')

In [ ]:
x_census = OneHotEncoder.fit_transform(x_census).toarray()

In [60]:
x_census

array([[39, 39, 77516, ..., 0, 40, ' United-States'],
       [50, 39, 83311, ..., 0, 13, ' United-States'],
       [38, 39, 215646, ..., 0, 40, ' United-States'],
       ...,
       [58, 39, 151910, ..., 0, 40, ' United-States'],
       [22, 39, 201490, ..., 0, 20, ' United-States'],
       [52, 39, 287927, ..., 0, 40, ' United-States']], dtype=object)

In [61]:
x_census[0]

array([39, 39, 77516, ' Bachelors', 13, ' Never-married', ' Adm-clerical',
       ' Not-in-family', ' White', ' Male', 2174, 0, 40, ' United-States'],
      dtype=object)

In [62]:
x_census.shape

(32561, 14)

## Escalonamento dos valores

De: valores com escalas diferentes (ex: age 17-90, education-num 1-16, hour-per-week1-99)
Para: valores com medidas proximas de 0 e desvios padrao proximos de 1

In [ ]:
scaler_census = StandardScaler()
x_census = scaler_census.fit_transform(x_census)

In [64]:
x_census[0]

array([39, 39, 77516, ' Bachelors', 13, ' Never-married', ' Adm-clerical',
       ' Not-in-family', ' White', ' Male', 2174, 0, 40, ' United-States'],
      dtype=object)

Divisao da base em treinamento e teste

In [68]:
x_census_treinamento, x_census_teste, y_census_treinamento, y_census_teste = train_test_split(x_census, y_census, test_size=0.15, random_state=0)

In [69]:
x_census_treinamento.shape, y_census_treinamento.shape

((27676, 14), (27676,))

In [70]:
x_census_teste.shape, y_census_teste.shape

((4885, 14), (4885,))

Salvar as variaveis

In [71]:
with open (caminho + "census.pkl", 'wb') as f:
  pickle.dump([x_census_treinamento, y_census_treinamento, x_census_teste, y_census_teste], f)